### ISSUE TITLE
BSOD when trying to read etc

### ISSUE THREAD

**Issue by evo15** [0mWindyBug/GhostMapperUM#3]
I get this issue when i map my driver with your mapper, standart kdmapper doesnt cause any issues..
BSOD ERROR: ATTEMPTED_WRITE_TO_READONLY_MEMORY
And Error origin: dump_stornvme.sys

lmk if u can help

**Comment by evo15** [comment]
as soon i am reading "physical memory" i bsod..

**Comment by evo15** [comment]
im not writing into memory either, just getting cr3( resolve dtb)  and reading physical memory 
I think this release a very nice one and i really want to fix this

**Comment by evo15** [comment]
With some debugging i found out as soon as i communicate with my driver i bsod doesnt matter what function. Any other mapper doesnt cause problems

**Comment by 0mWindyBug** [comment]
hmm, is your driver doing anything outside driver entry? did you comment out the restore original function call? because as mentioned in the readme, the original driver (the ghost driver) is restored once CallKernelFunction returns , read that part of the readme again

**Comment by evo15** [comment]
I did not comment it out actually, but wouldnt commenting this out would break the mappers intention?

**Comment by evo15** [comment]
nevermind, i think im opening some threads, doing shit outside the driver entry. But can you answer my question above?

**Comment by evo15** [comment]
commenting it out fixxed it i think, but as I said wouldnt that affect the projcets intention? Since it will leave the original driver (ghost driver) modified with all the patches

**Comment by evo15** [comment]
To your comment, "an example would be using a shared event to sync when your driver finished it's work , only then restore "
I don't quite understand what is meant by: "when your driver finished it's work"?
Appriciate every help btw!!!

**Comment by 0mWindyBug** [comment]
1. the main intention behind this release it to allow you to map your driver over signed driver , thus bypassing some heuristic detection vectors like nmi stack walking and apcs. saying that, patching a driver (even tho it doesn’t have a direct corresponding image on disk) is a vector we’d like to limit , so I provided you with a way to restore the original image and PTEs when your driver finished doing it’s work and you don’t need it anymore , you can synchronize it with a shared event (wait on the event in the mapper , signal it from the driver before finishing executing , once the mapper’s wait is satisfied - call RestoreOriginalDriver

**Comment by evo15** [comment]
thanks for explaining in detail, when do i reach the state where I dont need my driver anymore? I still didnt get when to restore. Yes, when i dont need it anymore.. but when is that? When i close my usermode and dont need the driver anymore to read something for example? Don’t mind my questions im still new and open to learn

**Comment by 0mWindyBug** [comment]
That would depend on your driver and the reason you load it in the first place , you might need it throughout so the restore part can be ignored , let’s say you load a driver to patch anti cheat kernel callbacks and obtain a handle to the game process with vm read and write , once you have the handle you can unmap the driver - ie restore

**Comment by evo15** [comment]
Wow ty for this. That was what i was looking for!!

**Comment by evo15** [comment]
can you accept my friend request on discord?

**Comment by 0mWindyBug** [comment]
ah, what is your username? (My discord is 0xwindybug)

**Comment by evo15** [comment]
> ah, what is your username? (My discord is 0xwindybug)

gshhhx

**Comment by 0mWindyBug** [comment]
Alright
