### ISSUE TITLE
No dump_stornvme driver

### ISSUE THREAD

**Issue by evo15** [0mWindyBug/GhostMapperUM#4]
Hey, for me it works perfect, but my friend has issues he cannot load dump_stornvme.sys / not loaded. the mapper cannot find that driver. How can i help him load the driver? I tried modifiying a few registry values but it didnt work. I'd appriciate a tiny hint or help. thanks in upfront!

**Comment by 0mWindyBug** [comment]
Try to map over dump_dumpfve.sys instead (in case this one is loaded), it’s a bit smaller in size tho so make sure it’s large enough to fit your driver. Lmk if it works, if not I’ll look into it myself when I have time

**Comment by evo15** [comment]
OK I will, ty
Can this also be solved with resintalling windows?

**Comment by evo15** [comment]
He tried, dump_dumpfve.sys isnt loaded either. i tried to help him somehow to load the dump drivers with the modified registry values but not working

**Comment by 0mWindyBug** [comment]
> He tried, dump_dumpfve.sys isnt loaded either. i tried to help him somehow to load the dump drivers with the modified registry values but not working


Is bitlocker enabled on his system?

**Comment by evo15** [comment]
BitLocker is off

**Comment by 0mWindyBug** [comment]
> BitLocker is off

Turn on
